#language: java
#sudo: false
#script: mvn clean verify package -DskipTests=true

sudo: required
language: java
script: mvn verify
services:
  - mysql
  - docker
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  artifacts: true
    
