sudo: required
language: java
script: mvn clean build
services:
  - docker
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  artifacts: true
    
