sudo: required
language: java
script: mvn verify
test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
services:
  - docker
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  artifacts: true