sudo: required
language: java
install: true
script: mvn clean package -DskipTests=true
# script: mvn clean compile package
services:
  - docker
deploy:
  provider: script
  script: bash docker_push.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  artifacts: true
    
